# Importing the Dependencies


In [2]:
import numpy as np
import pandas as pd
import difflib #closest match to the spelling error movies name from our dataset
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity



#Data Collection and Pre-Processing

In [3]:
#Data loading from csv file to pandas dataframe
movies_data = pd.read_csv("/content/movies.csv")

In [4]:
#printing first five rows of a dataframe
movies_data.head()

index  ...           director
0      0  ...      James Cameron
1      1  ...     Gore Verbinski
2      2  ...         Sam Mendes
3      3  ...  Christopher Nolan
4      4  ...     Andrew Stanton

[5 rows x 24 columns]

In [7]:
movies_data.shape
#dataset is quite small due to hardware constraint

(4803, 24)

In [8]:
#selecting the relevent features for recommendation feature
selected_features = ['genres', 'keywords', 'tagline','cast','director','overview']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [9]:
#Replacing the null value with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [11]:
#combining all the file selected feature

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']+' '+movies_data['overview']

In [12]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [13]:
#converting the text into feature vector
vectorizer = TfidfVectorizer()

In [14]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [15]:
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 307355 stored elements and shape (4803, 30592)>
  Coords	Values
  (0, 561)	0.05971816344971169
  (0, 703)	0.06846420517510078
  (0, 9754)	0.08513696797398294
  (0, 23977)	0.07941905576010944
  (0, 10023)	0.07960231361105431
  (0, 6601)	0.1498786462809525
  (0, 5279)	0.1549075340655008
  (0, 10796)	0.11095111375730655
  (0, 25413)	0.24369151759694266
  (0, 29469)	0.08637114089261566
  (0, 5592)	0.17322386697661618
  (0, 25232)	0.1336739112380023
  (0, 9065)	0.14505772980982928
  (0, 27118)	0.08328687324810813
  (0, 30121)	0.07272849549697494
  (0, 19410)	0.0318696249813729
  (0, 20039)	0.37747447361884223
  (0, 23619)	0.11047375838269538
  (0, 30145)	0.18243919685121024
  (0, 30543)	0.15064979633862852
  (0, 23578)	0.16802034155542864
  (0, 24802)	0.158925784923944
  (0, 29614)	0.15064979633862852
  (0, 25868)	0.11590870590502833
  (0, 15569)	0.171366691592621
  :	:
  (4802, 9588)	0.10415492266309316
  (4802, 21386)	0.0897551

#Cosine Similarity

In [17]:
#getting similarity confidence score using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [18]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [19]:
similarity.shape

(4803, 4803)

# Movie Recommendation System

In [44]:
#getting the user name from user
movie_name = input('Enter Your Favourite Movie Name:')
list_of_movies = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name,list_of_movies)

close_match = find_close_match[0]

#finding the index value
index_of_movies = movies_data[movies_data.title==close_match]['index'].values[0]

#getting the list of similar movies
similarity_score = list(enumerate(similarity[index_of_movies]))

#NOW SORTING THE MOVIES BASED ON THERE SIMILARITY SCORE
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

#print the name of similar movies based on the index

print('Movies Suggested for you: \n')
i=1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]['title'].values[0]
  if(i<=20):
    print(i ,'.',title_from_index)
    i+=1

Enter Your Favourite Movie Name:Avatar
Movies Suggested for you: 

1 . Avatar
2 . Lifeforce
3 . Moonraker
4 . Alien
5 . Star Trek Beyond
6 . Gattaca
7 . Aliens
8 . Guardians of the Galaxy
9 . Gravity
10 . Lockout
11 . Apollo 18
12 . Lost in Space
13 . Cargo
14 . Lara Croft Tomb Raider: The Cradle of Life
15 . Treasure Planet
16 . Men in Black
17 . Star Trek Into Darkness
18 . Zathura: A Space Adventure
19 . The Book of Life
20 . Sunshine
